server:
  port: 12680

spring:
  datasource:
    mysql-server:
      jdbc-url: jdbc:mysql://172.28.64.1:3306/radar?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

  kafka:
    bootstrap-servers: 172.28.64.1:9092
    zookeeper-connect: 172.28.64.1:2181
    producer:
      acks: 1
      batch-size: 163840
      linger-ms: 1000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:
    redis:
      database: 0
      host: 172.28.64.1
      port: 6379
      password: 123456
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 4
        max-wait: 5000

mybatis-plus:
  global-config:
    db-config:
      id-type: none
